backend:
  name: git-gateway
  branch: master
site_url: https://fatbrothers.netlify.com/
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/"
collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio Items" # Used in the UI
    preview_path: "portfolio"
    folder: "src/_cms/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden" }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "Name of project",
        }
      - {
          label: "Unique ID",
          name: "id",
          widget: "string",
          hint: "Used for interating",
        }
      - { label: "Tech used", name: "stack", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
